version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: url_media_save_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: media_save
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 